# Site settings
title: YM Blog
SEOTitle: 易木的博客 | YM Blog
header-img: img/background/post-bg-desk.jpg
email: yanglin9837@gmail.com
description: "Every failure is leading towards success."
keyword: "YM, YM Blog, 易木的博客, 易木, 博客, Jekyll, GitHub Pages, 个人博客, 个人网站, 个人主页, @lyricyang, Yeoh, Yang, homepage, 互联网, 后端, 全栈"
url: "https://blog.yeoh-yolo.com/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/LyricYang/LyricYang.github.io.git" # you code repository

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
github_username:    Lyricyang
linkedin_username:  lin-yang-733705341
twitter_username:   AaronYeohXY


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "docs",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "Readme.md",
    "Readme.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate, jekyll-sitemap]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: lyricyang

# Netease settings
netease_comment: false

# Sidebar settings
sidebar: true                                 # whether or not using Sidebar.
sidebar-about-description: "Get busy living, Or get busy dying!"
sidebar-avatar: /img/icon/about-YM-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Google Analytics
# 作用：指定 Google Analytics 的跟踪 ID，用于唯一标识你的 GA 属性。
# 格式：UA-xxxxxx-xx（Universal Analytics）或 G-XXXXXXXXXX（Google Analytics 4）。
# 用途：通过这个 ID，Google Analytics 能够将访问数据归属到你的账户。
ga_track_id: "G-4T13Q5BKW5"
# 作用：设置跟踪的域名范围。
# 默认值：auto，表示自动检测域名。
# 用途：如果你有自定义域名（如 example.com），可以设置为该域名。如果使用 GitHub Pages 的默认域名（如 username.github.io），可以保持为 auto。
ga_domain: blog.yeoh-yolo.com

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
        title: "Product Hunt",
        href: "https://www.producthunt.com/"
    },{
        title: "Tech Crunch",
        href: "https://techcrunch.com/"
    },{
        title: "Rebang.Today",
        href: "https://rebang.today/tech"
    },{
        title: "Dribbble",
        href: "https://dribbble.com"
    },{
        title: "11ElevenLabs",
        href: "https://elevenlabs.io"
    },{
        title: "有趣网站之家",
        href: "https://youquhome.com/"
    }
]
